version: '3'
services:
  nats:
    image: docker.pkg.github.com/dioptre/nats/nats:latest
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
    networks:
      - default
    container_name: nats
  cassandra:
    image: docker.pkg.github.com/dioptre/elassandra-docker/elassandra:latest
    ports:
      - "9042:9042"
      - "9160:9160"
    networks: 
      - default  
    # hostname: cassandra
    container_name: cassandra
    volumes: 
      - ./xcs/.setup:/tmp/.csetup
    command: >
              bash -c "((sleep 90s && cqlsh --ssl -f /tmp/.csetup/schema/cassandra/schema.1.cql &) && (/docker-entrypoint.sh cassandra -f))"
  